### PR TITLE
Added Dutch placeholder translations

### PR DESCRIPTION
**Pull request by Vistaus**
🙂

### CODE REVIEW

**Comment by Nyre221** [comment]
Thanks for contributing to this project :)
I updated to the latest version and you can download it from here: https://www.pling.com/p/1952905/

**Comment by Nyre221** [comment]
@Vistaus Is it ok to have the translation loaded when the LANG variable in the system is nl_Nl or de_DE? I changed the system language and noticed that there are two netherlands languages listed, dutch and nederlands, and i don't understand the difference. Isn't dutch one of the official languages and nederlands is just the name of the country?

**Comment by Vistaus** [comment]
@Nyre221 Hmm, on my system, there's only Nederlands available.

_Nederland_ is the name of the country; _Nederlands_ is the language we speak in most of the country (in English it's called _Dutch_).

**Comment by Nyre221** [comment]
@Vistaus  You are right. The names are written in the original language and I got confused with a similar name. 
I made a very stupid mistake, sorry.

**Comment by Vistaus** [comment]
Don't worry about it! :-)

**Pull request merged**
